version: '3.7'

services:
  crudapi_db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: test
      POSTGRES_DB: crudapi
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - "7432:5432"

volumes:
  database-data: