// Code generated by entc, DO NOT EDIT.

package pizza

import (
	"fmt"
	"time"
)

const (
	// Label holds the string label denoting the pizza type in the database.
	Label = "pizza"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldPrice holds the string denoting the price field in the database.
	FieldPrice = "price"
	// FieldDough holds the string denoting the dough field in the database.
	FieldDough = "dough"
	// Table holds the table name of the pizza in the database.
	Table = "pizzas"
)

// Columns holds all SQL columns for pizza fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldUpdateTime,
	FieldTitle,
	FieldDescription,
	FieldPrice,
	FieldDough,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
	// TitleValidator is a validator for the "title" field. It is called by the builders before save.
	TitleValidator func(string) error
	// DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	DescriptionValidator func(string) error
	// PriceValidator is a validator for the "price" field. It is called by the builders before save.
	PriceValidator func(int64) error
)

// Dough defines the type for the "dough" enum field.
type Dough string

// DoughThick is the default value of the Dough enum.
const DefaultDough = DoughThick

// Dough values.
const (
	DoughThick Dough = "thick"
	DoughThin  Dough = "thin"
)

func (d Dough) String() string {
	return string(d)
}

// DoughValidator is a validator for the "dough" field enum values. It is called by the builders before save.
func DoughValidator(d Dough) error {
	switch d {
	case DoughThick, DoughThin:
		return nil
	default:
		return fmt.Errorf("pizza: invalid enum value for dough field: %q", d)
	}
}
